# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f21a9576edeb09a0449c2acd9711d69a1aaacee3bed9edde14316c3d25b874fe697e340c41e0faccdad387ceef5347986714bbdb5045b7cf9ee49654b36e3ef

test:
  secret_key_base: 4bea530a1fd8824a548bb64d44de32a11f1e65d349eb997645aae52b720f2ee470b38ffa161594265d46a24bdf6f9724397d4c4dad9ce6328d0d3e6bca15402c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
